### ISSUE TITLE
stl import problem

### ISSUE THREAD

**Issue by michal777** [thliebig/openEMS-Project#6]
Hi
I tried to import stl 3D file to openems and got an error
[bug_stl.txt](https://github.com/thliebig/openEMS-Project/files/2756786/bug_stl.txt)

The openEMS complains that it can't find my stl file but QCSXCAD displayed it (so it's there).

I tried on fresh update on linux mint, tried also on windows (earlier version - installed from available installer).

**Comment by thliebig** [comment]
You should post such issues on the openEMS forum please. Especially since that is most likely a user error. My hint, please use a full path to the stl file instead of just the name itself. openEMS and QCSXCAD otherwise search the file at different current working directories and thus do or do not find it.

**Comment by michal777** [comment]
With full path it works :) Thanks for the answer and sorry for posting in wrong place.
