### ISSUE TITLE
Like to run OpenEMS on a patch antenna under Windows.

### ISSUE THREAD

**Issue by TahhaR** [thliebig/openEMS-Project#66]
Hello people,
i created my own patch antenna and want to simulate it through OpenEMS but i get problems during or after a long while of simulation ( the last one lasted for more than one hour of copilation). I generate an automatic script with Freecad_to_OpenEMS_Export. I run the already existing examples and they ran easily and the Energy was not as the same as mine . So if you could help it would be nice. Thanks in advance.
![Ergebnis_Simulation](https://github.com/thliebig/openEMS-Project/assets/61636792/75dfe1e9-69d7-4e1a-8367-a54220118fbf)

**Comment by LubomirJagos** [comment]
Hi, really depends on your script what you generated, since you use that GUI addon your simulation should be generated right in sense that it displayed in AppCSXCAD right (all parts were placed on correct place). Most common issue since energy is not decreasing could be that mesh is generated wrong, must be corssing PEC material, substrate, also maybe some of generated gridlines are too close to each other therefore timestep is too small.
It would be more helpful to post at least screenshot of your antenna in AppCSXCAD or generated .m script

**Comment by LubomirJagos** [comment]
Looking that you opened this as issue is not right, you can post it into discussion, but this is not openEMS issue, openEMS is running fine, but your simulation is generated wrong, so if you can please close it here and create discussion topic for this.

**Comment by TahhaR** [comment]
Ok Thanks for the answer. i ll open a new discussion topic.

**Comment by TahhaR** [comment]
Hi,

I started the discussion if you want more infos don’t hesitate to ask o
write me anytime.
It’s the first time i start a discussion on Github 😆

**Comment by TahhaR** [comment]
Hi Lubomir,
can you please help me out to understand the Meshing, because i doubt on it
and i have red that´s very important for OpenEMS. That´s why, i would do it
manually. If you do have some examples please let me know. Thank you in
advance and have a nice weekend.
Best regards
Tahhar from Github

Le ven. 12 mai 2023 à 19:19, Lubomir Jagos ***@***.***> a
écrit :
